### ISSUE TITLE
不能上传           提示 部分数据加载失败，可能导致页面显示异常，请刷新充实

### ISSUE THREAD

**Issue by zqh2333** [rubyangxg/jd-qinglong#13]

**Comment by zqh2333** [comment]
ERROR 79 --- [nio-8080-exec-4] o.a.c.c.C.[.[.[/].[dispatcherServ                                                                    
let]    : Servlet.service() for servlet [dispatcherServlet] in context with path [] thre                                                                    
w exception [Request processing failed; nested exception is java.lang.NullPointerExcepti                                                                    
on] with root cause                                                                                                                                         
                                                                                                                                                            
java.lang.NullPointerException: null                                                                                                                        
        at com.meread.selenium.JDService.uploadQingLongWithToken(JDService.java:542) ~[c                                                                    
lasses!/:1.0]                                                                                                                                               
        at com.meread.selenium.HelloController.uploadQingLong(HelloController.java:221)                                                                     
~[classes!/:1.0]                                                                                                                                            
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method                                                                    
) ~[na:na]                                                                                                                                                  
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAc                                                                    
cessorImpl.java:62) ~[na:na]                                                                                                                                
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Delegating                                                                    
MethodAccessorImpl.java:43) ~[na:na]                                                                                                                        
        at java.base/java.lang.reflect.Method.invoke(Method.java:566) ~[na:na]                                                                              
        at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(Invoca                                                                    
bleHandlerMethod.java:190) ~[spring-web-5.2.15.RELEASE.jar!/:5.2.15.RELEASE]                                                                                
        at org.springframework.web.method.support.InvocableHandlerMethod.invokeForReques                                                                    
t(InvocableHandlerMethod.java:138) ~[spring-web-5.2.15.RELEASE.jar!/:5.2.15.RELEASE]                                                                        
        at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandler                                                                    
Method.invokeAndHandle(ServletInvocableHandlerMethod.java:105) ~[spring-webmvc-5.2.15.RE                                                                    
LEASE.jar!/:5.2.15.RELEASE]                                                                                                                                 
        at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAd                                                                    
apter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:878) ~[spring-webmvc-5.2.15.                                                                    
RELEASE.jar!/:5.2.15.RELEASE]

**Comment by zqh2333** [comment]
2021-09-21 15:06:46.935  INFO 93 --- [nio-8080-exec-6] com.meread.selenium.JDService            : getJDCookies ce30ef3fdca986c6bb4f6a8f282cfa92,https://plogin.m.jd.com/login/login?appid=300&returnurl=https%3A%2F%2Fwq.jd.com%2Fpassport%2FLoginRedirect%3Fstate%3D1101624461975%26returnurl%3Dhttps%253A%252F%252Fhome.m.jd.com%252FmyJd%252Fnewhome.action%253Fsceneval%253D2%2526ufc%253D%2526&source=wq_passport,
2021-09-21 15:06:47.100  INFO 93 --- [nio-8080-exec-6] com.meread.selenium.JDService            : ce30ef3fdca986c6bb4f6a8f282cfa92 expire 125,
2021-09-21 15:06:47.100  INFO 93 --- [nio-8080-exec-6] com.meread.selenium.JDService            : ce30ef3fdca986c6bb4f6a8f282cfa92 expire 125,
2021-09-21 15:06:48.942  INFO 93 --- [nio-8080-exec-8] com.meread.selenium.JDService            : getJDCookies ce30ef3fdca986c6bb4f6a8f282cfa92,https://plogin.m.jd.com/login/login?appid=300&returnurl=https%3A%2F%2Fwq.jd.com%2Fpassport%2FLoginRedirect%3Fstate%3D1101624461975%26returnurl%3Dhttps%253A%252F%252Fhome.m.jd.com%252FmyJd%252Fnewhome.action%253Fsceneval%253D2%2526ufc%253D%2526&source=wq_passport,
2021-09-21 15:06:49.097  INFO 93 --- [nio-8080-exec-8] com.meread.selenium.JDService            : ce30ef3fdca986c6bb4f6a8f282cfa92 expire 123,
2021-09-21 15:06:49.097  INFO 93 --- [nio-8080-exec-8] com.meread.selenium.JDService            : ce30ef3fdca986c6bb4f6a8f282cfa92 expire 123,
2021-09-21 15:06:50.970  INFO 93 --- [io-8080-exec-10] com.meread.selenium.JDService            : getJDCookies ce30ef3fdca986c6bb4f6a8f282cfa92,https://plogin.m.jd.com/login/login?appid=300&returnurl=https%3A%2F%2Fwq.jd.com%2Fpassport%2FLoginRedirect%3Fstate%3D1101624461975%26returnurl%3Dhttps%253A%252F%252Fhome.m.jd.com%252FmyJd%252Fnewhome.action%253Fsceneval%253D2%2526ufc%253D%2526&source=wq_passport,
2021-09-21 15:06:51.121  INFO 93 --- [io-8080-exec-10] com.meread.selenium.JDService            : ce30ef3fdca986c6bb4f6a8f282cfa92 expire 121,
2021-09-21 15:06:51.121  INFO 93 --- [io-8080-exec-10] com.meread.selenium.JDService            : ce30ef3fdca986c6bb4f6a8f282cfa92 expire 121,
2021-09-21 15:06:53.055  INFO 93 --- [nio-8080-exec-3] com.meread.selenium.JDService            : getJDCookies ce30ef3fdca986c6bb4f6a8f282cfa92,https://plogin.m.jd.com/login/login?appid=300&returnurl=https%3A%2F%2Fwq.jd.com%2Fpassport%2FLoginRedirect%3Fstate%3D1101624461975%26returnurl%3Dhttps%253A%252F%252Fhome.m.jd.com%252FmyJd%252Fnewhome.action%253Fsceneval%253D2%2526ufc%253D%2526&source=wq_passport,
2021-09-21 15:06:53.227  INFO 93 --- [nio-8080-exec-3] com.meread.selenium.JDService            : ce30ef3fdca986c6bb4f6a8f282cfa92 expire 119,
2021-09-21 15:06:53.227  INFO 93 --- [nio-8080-exec-3] com.meread.selenium.JDService            : ce30ef3fdca986c6bb4f6a8f282cfa92 expire 119,
2021-09-21 15:06:55.005  INFO 93 --- [nio-8080-exec-9] com.meread.selenium.JDService            : getJDCookies ce30ef3fdca986c6bb4f6a8f282cfa92,https://plogin.m.jd.com/login/login?appid=300&returnurl=https%3A%2F%2Fwq.jd.com%2Fpassport%2FLoginRedirect%3Fstate%3D1101624461975%26returnurl%3Dhttps%253A%252F%252Fhome.m.jd.com%252FmyJd%252Fnewhome.action%253Fsceneval%253D2%2526ufc%253D%2526&source=wq_passport,
2021-09-21 15:06:55.199  INFO 93 --- [nio-8080-exec-9] com.meread.selenium.JDService            : ce30ef3fdca986c6bb4f6a8f282cfa92 expire 117,
2021-09-21 15:06:55.200  INFO 93 --- [nio-8080-exec-9] com.meread.selenium.JDService            : ce30ef3fdca986c6bb4f6a8f282cfa92 expire 117,
2021-09-21 15:06:56.999  INFO 93 --- [nio-8080-exec-5] com.meread.selenium.JDService            : getJDCookies ce30ef3fdca986c6bb4f6a8f282cfa92,https://plogin.m.jd.com/login/login?appid=300&returnurl=https%3A%2F%2Fwq.jd.com%2Fpassport%2FLoginRedirect%3Fstate%3D1101624461975%26returnurl%3Dhttps%253A%252F%252Fhome.m.jd.com%252FmyJd%252Fnewhome.action%253Fsceneval%253D2%2526ufc%253D%2526&source=wq_passport,
2021-09-21 15:06:57.194  INFO 93 --- [nio-8080-exec-5] com.meread.selenium.JDService            : ce30ef3fdca986c6bb4f6a8f282cfa92 expire 115,
2021-09-21 15:06:57.194  INFO 93 --- [nio-8080-exec-5] com.meread.selenium.JDService            : ce30ef3fdca986c6bb4f6a8f282cfa92 expire 115,
2021-09-21 15:06:58.936  INFO 93 --- [nio-8080-exec-4] com.meread.selenium.JDService            : getJDCookies ce30ef3fdca986c6bb4f6a8f282cfa92,https://plogin.m.jd.com/login/login?appid=300&returnurl=https%3A%2F%2Fwq.jd.com%2Fpassport%2FLoginRedirect%3Fstate%3D1101624461975%26returnurl%3Dhttps%253A%252F%252Fhome.m.jd.com%252FmyJd%252Fnewhome.action%253Fsceneval%253D2%2526ufc%253D%2526&source=wq_passport,
2021-09-21 15:06:59.113  INFO 93 --- [nio-8080-exec-4] com.meread.selenium.JDService            : ce30ef3fdca986c6bb4f6a8f282cfa92 expire 113,
2021-09-21 15:06:59.114  INFO 93 --- [nio-8080-exec-4] com.meread.selenium.JDService            : ce30ef3fdca986c6bb4f6a8f282cfa92 expire 113,
2021-09-21 15:07:00.971  INFO 93 --- [nio-8080-exec-7] com.meread.selenium.JDService            : getJDCookies ce30ef3fdca986c6bb4f6a8f282cfa92,https://plogin.m.jd.com/login/login?appid=300&returnurl=https%3A%2F%2Fwq.jd.com%2Fpassport%2FLoginRedirect%3Fstate%3D1101624461975%26returnurl%3Dhttps%253A%252F%252Fhome.m.jd.com%252FmyJd%252Fnewhome.action%253Fsceneval%253D2%2526ufc%253D%2526&source=wq_passport,
2021-09-21 15:07:01.150  INFO 93 --- [nio-8080-exec-7] com.meread.selenium.JDService            : ce30ef3fdca986c6bb4f6a8f282cfa92 expire 111,
2021-09-21 15:07:01.150  INFO 93 --- [nio-8080-exec-7] com.meread.selenium.JDService            : ce30ef3fdca986c6bb4f6a8f282cfa92 expire 111,
2021-09-21 15:07:01.646  INFO 93 --- [nio-8080-exec-8] com.meread.selenium.JDService            : getJDCookies ce30ef3fdca986c6bb4f6a8f282cfa92,https://plogin.m.jd.com/login/login?appid=300&returnurl=https%3A%2F%2Fwq.jd.com%2Fpassport%2FLoginRedirect%3Fstate%3D1101624461975%26returnurl%3Dhttps%253A%252F%252Fhome.m.jd.com%252FmyJd%252Fnewhome.action%253Fsceneval%253D2%2526ufc%253D%2526&source=wq_passport,
2021-09-21 15:07:01.836  INFO 93 --- [nio-8080-exec-8] com.meread.selenium.JDService            : ce30ef3fdca986c6bb4f6a8f282cfa92 expire 110,
2021-09-21 15:07:01.837  INFO 93 --- [nio-8080-exec-8] com.meread.selenium.JDService            : ce30ef3fdca986c6bb4f6a8f282cfa92 expire 110,
2021-09-21 15:07:02.955  INFO 93 --- [io-8080-exec-10] com.meread.selenium.JDService            : getJDCookies ce30ef3fdca986c6bb4f6a8f282cfa92,https://plogin.m.jd.com/login/login?appid=300&returnurl=https%3A%2F%2Fwq.jd.com%2Fpassport%2FLoginRedirect%3Fstate%3D1101624461975%26returnurl%3Dhttps%253A%252F%252Fhome.m.jd.com%252FmyJd%252Fnewhome.action%253Fsceneval%253D2%2526ufc%253D%2526&source=wq_passport,
2021-09-21 15:07:03.118  INFO 93 --- [io-8080-exec-10] com.meread.selenium.JDService            : ce30ef3fdca986c6bb4f6a8f282cfa92 expire 109,
2021-09-21 15:07:03.118  INFO 93 --- [io-8080-exec-10] com.meread.selenium.JDService            : ce30ef3fdca986c6bb4f6a8f282cfa92 expire 109,
2021-09-21 15:07:03.321  INFO 93 --- [nio-8080-exec-1] com.meread.selenium.JDService            : getJDCookies ce30ef3fdca986c6bb4f6a8f282cfa92,https://plogin.m.jd.com/login/login?appid=300&returnurl=https%3A%2F%2Fwq.jd.com%2Fpassport%2FLoginRedirect%3Fstate%3D1101624461975%26returnurl%3Dhttps%253A%252F%252Fhome.m.jd.com%252FmyJd%252Fnewhome.action%253Fsceneval%253D2%2526ufc%253D%2526&source=wq_passport,
2021-09-21 15:07:03.477  INFO 93 --- [nio-8080-exec-1] com.meread.selenium.JDService            : ce30ef3fdca986c6bb4f6a8f282cfa92 expire 109,
2021-09-21 15:07:03.477  INFO 93 --- [nio-8080-exec-1] com.meread.selenium.JDService            : ce30ef3fdca986c6bb4f6a8f282cfa92 expire 109,
15:07:03.684 WARN [SeleniumSpanExporter$1.lambda$export$0] - {"traceId": "8d0e89cb78e0570f6376cffeaf5301da","eventTime": 1632236823684130785,"eventName": "HTTP request execution complete","attributes": {"http.flavor": 1,"http.handler_class": "org.openqa.selenium.remote.http.Route$PredicatedRoute","http.host": "localhost:4444","http.method": "POST","http.request_content_length": "55","http.scheme": "HTTP","http.status_code": 500,"http.target": "\u002fsession\u002fce30ef3fdca986c6bb4f6a8f282cfa92\u002fexecute\u002fsync","http.user_agent": "selenium\u002f4.0.0-rc-1 (java unix)"}},
,
2021-09-21 15:07:04.953  INFO 93 --- [nio-8080-exec-2] com.meread.selenium.JDService            : getJDCookies ce30ef3fdca986c6bb4f6a8f282cfa92,https://plogin.m.jd.com/login/login?appid=300&returnurl=https%3A%2F%2Fwq.jd.com%2Fpassport%2FLoginRedirect%3Fstate%3D1101624461975%26returnurl%3Dhttps%253A%252F%252Fhome.m.jd.com%252FmyJd%252Fnewhome.action%253Fsceneval%253D2%2526ufc%253D%2526&source=wq_passport,
2021-09-21 15:07:04.974  INFO 93 --- [nio-8080-exec-2] com.meread.selenium.JDService            : ce30ef3fdca986c6bb4f6a8f282cfa92 expire 107,
2021-09-21 15:07:04.975  INFO 93 --- [nio-8080-exec-2] com.meread.selenium.HelloController      : 已经获取到ck了 ce30ef3fdca986c6bb4f6a8f282cfa92, ck = pt_key=AAJhSfUXADDy06yHXxGyFZcHiLzJyMhMhV4U4ap3WJpfuyP2rcMIwy06d9qofUF1lJnLVFb5nFQ;pt_pin=jd_zrnrvBSjMuqf;,
2021-09-21 15:07:04.976  INFO 93 --- [nio-8080-exec-2] com.meread.selenium.HelloController      : doXDDNotify res = null,
2021-09-21 15:07:08.295  INFO 93 --- [nio-8080-exec-3] com.meread.selenium.JDService            : getJDCookies ce30ef3fdca986c6bb4f6a8f282cfa92,https://m.jd.com/,
2021-09-21 15:07:08.312  INFO 93 --- [nio-8080-exec-3] com.meread.selenium.JDService            : ce30ef3fdca986c6bb4f6a8f282cfa92 expire 104,
2021-09-21 15:07:08.312  INFO 93 --- [nio-8080-exec-3] com.meread.selenium.HelloController      : 已经获取到ck了 ce30ef3fdca986c6bb4f6a8f282cfa92, ck = pt_key=AAJhSfUXADDy06yHXxGyFZcHiLzJyMhMhV4U4ap3WJpfuyP2rcMIwy06d9qofUF1lJnLVFb5nFQ;pt_pin=jd_zrnrvBSjMuqf;,
2021-09-21 15:07:08.312  INFO 93 --- [nio-8080-exec-3] com.meread.selenium.HelloController      : doXDDNotify res = null,
2021-09-21 15:07:15.847  INFO 93 --- [nio-8080-exec-5] com.meread.selenium.JDService            : 开始获取当前ck数量http://10.10.10.5:5700/open/envs?searchValue=&t=1632236835847,
2021-09-21 15:07:15.917 ERROR 93 --- [nio-8080-exec-5] o.a.c.c.C.[.[.[/].[dispatcherServlet]    : Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed; nested exception is java.lang.NullPointerException] with root cause,
,
java.lang.NullPointerException: null,
	at com.meread.selenium.JDService.uploadQingLongWithToken(JDService.java:545) ~[classes!/:1.0],
	at com.meread.selenium.HelloController.uploadQingLong(HelloController.java:221) ~[classes!/:1.0],
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na],
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:na],
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na],
	at java.base/java.lang.reflect.Method.invoke(Method.java:566) ~[na:na],
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:190) ~[spring-web-5.2.15.RELEASE.jar!/:5.2.15.RELEASE],
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:138) ~[spring-web-5.2.15.RELEASE.jar!/:5.2.15.RELEASE],
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:105) ~[spring-webmvc-5.2.15.RELEASE.jar!/:5.2.15.RELEASE],
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:878) ~[spring-webmvc-5.2.15.RELEASE.jar!/:5.2.15.RELEASE],
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:792) ~[spring-webmvc-5.2.15.RELEASE.jar!/:5.2.15.RELEASE],
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87) ~[spring-webmvc-5.2.15.RELEASE.jar!/:5.2.15.RELEASE],
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1040) ~[spring-webmvc-5.2.15.RELEASE.jar!/:5.2.15.RELEASE],
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:943) ~[spring-webmvc-5.2.15.RELEASE.jar!/:5.2.15.RELEASE],
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006) ~[spring-webmvc-5.2.15.RELEASE.jar!/:5.2.15.RELEASE],
	at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:909) ~[spring-webmvc-5.2.15.RELEASE.jar!/:5.2.15.RELEASE],
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:652) ~[tomcat-embed-core-9.0.46.jar!/:na],
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:883) ~[spring-webmvc-5.2.15.RELEASE.jar!/:5.2.15.RELEASE],
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:733) ~[tomcat-embed-core-9.0.46.jar!/:na],
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:227) ~[tomcat-embed-core-9.0.46.jar!/:na],
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162) ~[tomcat-embed-core-9.0.46.jar!/:na],
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53) ~[tomcat-embed-websocket-9.0.46.jar!/:na],
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189) ~[tomcat-embed-core-9.0.46.jar!/:na],
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162) ~[tomcat-embed-core-9.0.46.jar!/:na],
	at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100) ~[spring-web-5.2.15.RELEASE.jar!/:5.2.15.RELEASE],
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119) ~[spring-web-5.2.15.RELEASE.jar!/:5.2.15.RELEASE],
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189) ~[tomcat-embed-core-9.0.46.jar!/:na],
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162) ~[tomcat-embed-core-9.0.46.jar!/:na],
	at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:93) ~[spring-web-5.2.15.RELEASE.jar!/:5.2.15.RELEASE],
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119) ~[spring-web-5.2.15.RELEASE.jar!/:5.2.15.RELEASE],
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189) ~[tomcat-embed-core-9.0.46.jar!/:na],
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162) ~[tomcat-embed-core-9.0.46.jar!/:na],
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201) ~[spring-web-5.2.15.RELEASE.jar!/:5.2.15.RELEASE],
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119) ~[spring-web-5.2.15.RELEASE.jar!/:5.2.15.RELEASE],
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189) ~[tomcat-embed-core-9.0.46.jar!/:na],
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162) ~[tomcat-embed-core-9.0.46.jar!/:na],
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202) ~[tomcat-embed-core-9.0.46.jar!/:na],
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:97) ~[tomcat-embed-core-9.0.46.jar!/:na],
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:542) ~[tomcat-embed-core-9.0.46.jar!/:na],
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:143) ~[tomcat-embed-core-9.0.46.jar!/:na],
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92) ~[tomcat-embed-core-9.0.46.jar!/:na],
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78) ~[tomcat-embed-core-9.0.46.jar!/:na],
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:357) ~[tomcat-embed-core-9.0.46.jar!/:na],
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:374) ~[tomcat-embed-core-9.0.46.jar!/:na],
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65) ~[tomcat-embed-core-9.0.46.jar!/:na],
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:893) ~[tomcat-embed-core-9.0.46.jar!/:na],
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1707) ~[tomcat-embed-core-9.0.46.jar!/:na],
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49) ~[tomcat-embed-core-9.0.46.jar!/:na],
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[na:na],
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[na:na],
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) ~[tomcat-embed-core-9.0.46.jar!/:na],
	at java.base/java.lang.Thread.run(Thread.java:829) ~[na:na],
,

**Comment by rubyangxg** [comment]
此问题已修复，原因出在后台青龙中有一个key=JD_COOKIE, 但是value是随便填的 或者不符合pt_key=xxx;pt_pin=xxx;格式，请重新拉镜像
