### ISSUE TITLE
1.6版本5701端口页面加载不出来

### ISSUE THREAD

**Issue by hs20073** [rubyangxg/jd-qinglong#56]
[root@ql-ct8 jdql]# docker logs jd-login
2021-10-30 12:03:18,794 CRIT Supervisor is running as root.  Privileges were not dropped because no user is specified in the config file.  If you intend to run as root, you can set user=root in the config file to avoid this message.
2021-10-30 12:03:18,800 INFO RPC interface 'supervisor' initialized
2021-10-30 12:03:18,801 CRIT Server 'unix_http_server' running without any HTTP authentication checking
2021-10-30 12:03:18,801 INFO supervisord started with pid 1
2021-10-30 12:03:19,806 INFO spawned: 'guide' with pid 7
2021-10-30 12:03:19,809 INFO spawned: 'qqbot' with pid 8
2021-10-30 12:03:19,813 INFO spawned: 'selenoid' with pid 9
2021-10-30 12:03:19,818 INFO spawned: 'webapp' with pid 10
2021/10/30 12:03:19 [-] [INIT] [Loading configuration files...]
2021/10/30 12:03:19 [-] [INIT] [Loaded configuration from /etc/selenoid/browsers.json]
2021-10-30 12:03:19,840 INFO success: guide entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
2021-10-30 12:03:19,840 INFO success: qqbot entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
2021-10-30 12:03:19,840 INFO success: selenoid entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
2021-10-30 12:03:19,840 INFO success: webapp entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
2021/10/30 12:03:19 [-] [INIT] [Video Dir: /video]
2021/10/30 12:03:19 [-] [INIT] [Your Docker API version is 1.41]
2021/10/30 12:03:19 [-] [INIT] [Timezone: UTC]
2021/10/30 12:03:19 [-] [INIT] [Listening on :4444]
2021-10-30 12:03:21,366 INFO reaped unknown pid 26 (exit status 0)
2021-10-30 12:03:22,549 INFO exited: qqbot (exit status 1; not expected)

  .   ____          _            __ _ _
 /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
 \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
  '  |____| .__|_| |_|_| |_\__, | / / / /
 =========|_|==============|___/=/_/_/_/
 :: Spring Boot ::       (v2.3.12.RELEASE)

2021-10-30 20:03:23.161  INFO 7 --- [  restartedMain] c.m.selenium.GuideWebSocketApplication   : Starting GuideWebSocketApplication v1.0 on 5366c5154b76 with PID 7 (/guide.jar started by root in /)
2021-10-30 20:03:23.191  INFO 7 --- [  restartedMain] c.m.selenium.GuideWebSocketApplication   : The following profiles are active: ws
2021-10-30 20:03:23.452  INFO 7 --- [  restartedMain] .e.DevToolsPropertyDefaultsPostProcessor : Devtools property defaults active! Set 'spring.devtools.add-properties' to 'false' to disable
2021-10-30 20:03:23.453  INFO 7 --- [  restartedMain] .e.DevToolsPropertyDefaultsPostProcessor : For additional web related logging consider setting the 'logging.level.web' property to 'DEBUG'
2021-10-30 20:03:23.653  INFO 10 --- [           main] o.s.boot.SpringApplication               : Starting application on 5366c5154b76 with PID 10 (started by root in /)
2021-10-30 20:03:23.673  INFO 10 --- [           main] o.s.boot.SpringApplication               : No active profile set, falling back to default profiles: default
2021-10-30 20:03:23.897  INFO 10 --- [           main] .e.DevToolsPropertyDefaultsPostProcessor : For additional web related logging consider setting the 'logging.level.web' property to 'DEBUG'
2021-10-30 20:03:24.071  WARN 10 --- [kground-preinit] o.s.h.c.j.Jackson2ObjectMapperBuilder    : For Jackson Kotlin classes support please add "com.fasterxml.jackson.module:jackson-module-kotlin" to the classpath
2021-10-30 20:03:27.712  INFO 7 --- [  restartedMain] o.s.b.w.embedded.tomcat.TomcatWebServer  : Tomcat initialized with port(s): 8090 (http)
2021-10-30 20:03:27.748  INFO 7 --- [  restartedMain] o.apache.catalina.core.StandardService   : Starting service [Tomcat]
2021-10-30 20:03:27.748  INFO 7 --- [  restartedMain] org.apache.catalina.core.StandardEngine  : Starting Servlet engine: [Apache Tomcat/9.0.46]
2021-10-30 20:03:27.924  INFO 7 --- [  restartedMain] o.a.c.c.C.[Tomcat].[localhost].[/]       : Initializing Spring embedded WebApplicationContext
2021-10-30 20:03:27.924  INFO 7 --- [  restartedMain] w.s.c.ServletWebServerApplicationContext : Root WebApplicationContext: initialization completed in 4471 ms
2021-10-30 20:03:29.933  INFO 10 --- [           main] o.s.b.w.embedded.tomcat.TomcatWebServer  : Tomcat initialized with port(s): 8080 (http)
2021-10-30 20:03:29.994  INFO 10 --- [           main] o.apache.catalina.core.StandardService   : Starting service [Tomcat]
2021-10-30 20:03:29.994  INFO 10 --- [           main] org.apache.catalina.core.StandardEngine  : Starting Servlet engine: [Apache Tomcat/9.0.46]
2021-10-30 20:03:30.292  INFO 10 --- [           main] o.a.c.c.C.[Tomcat].[localhost].[/]       : Initializing Spring embedded WebApplicationContext
2021-10-30 20:03:30.292  INFO 10 --- [           main] w.s.c.ServletWebServerApplicationContext : Root WebApplicationContext: initialization completed in 6394 ms
2021-10-30 20:03:31.643  WARN 7 --- [  restartedMain] ConfigServletWebServerApplicationContext : Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'webSocketConfig': Unsatisfied dependency expressed through field 'qqEventHandler'; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'guideEventHandler': Unsatisfied dependency expressed through field 'wsProcessor'; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'guideWSProcessor': Unsatisfied dependency expressed through field 'nodeService'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'nodeService' defined in URL [jar:file:/jarlib/jd-qinglong-service-1.0.jar!/com/meread/selenium/service/NodeService.class]: Invocation of init method failed; nested exception is java.io.FileNotFoundException: class path resource [ql.db] cannot be opened because it does not exist
2021-10-30 20:03:31.659  INFO 7 --- [  restartedMain] o.apache.catalina.core.StandardService   : Stopping service [Tomcat]
2021-10-30 20:03:31.732  INFO 7 --- [  restartedMain] ConditionEvaluationReportLoggingListener :

Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
2021-10-30 20:03:31.828 ERROR 7 --- [  restartedMain] o.s.boot.SpringApplication               : Application run failed

org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'webSocketConfig': Unsatisfied dependency expressed through field 'qqEventHandler'; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'guideEventHandler': Unsatisfied dependency expressed through field 'wsProcessor'; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'guideWSProcessor': Unsatisfied dependency expressed through field 'nodeService'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'nodeService' defined in URL [jar:file:/jarlib/jd-qinglong-service-1.0.jar!/com/meread/selenium/service/NodeService.class]: Invocation of init method failed; nested exception is java.io.FileNotFoundException: class path resource [ql.db] cannot be opened because it does not exist
        at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.resolveFieldValue(AutowiredAnnotationBeanPostProcessor.java:660) ~[spring-beans-5.2.15.RELEASE.jar:5.2.15.RELEASE]
        at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:640) ~[spring-beans-5.2.15.RELEASE.jar:5.2.15.RELEASE]
        at org.springframework.beans.factory.annotation.InjectionMetadata.inject(InjectionMetadata.java:119) ~[spring-beans-5.2.15.RELEASE.jar:5.2.15.RELEASE]
        at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.postProcessProperties(AutowiredAnnotationBeanPostProcessor.java:399) ~[spring-beans-5.2.15.RELEASE.jar:5.2.15.RELEASE]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1425) ~[spring-beans-5.2.15.RELEASE.jar:5.2.15.RELEASE]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:593) ~[spring-beans-5.2.15.RELEASE.jar:5.2.15.RELEASE]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:516) ~[spring-beans-5.2.15.RELEASE.jar:5.2.15.RELEASE]
        at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:324) ~[spring-beans-5.2.15.RELEASE.jar:5.2.15.RELEASE]
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234) ~[spring-beans-5.2.15.RELEASE.jar:5.2.15.RELEASE]
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:322) ~[spring-beans-5.2.15.RELEASE.jar:5.2.15.RELEASE]
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:202) ~[spring-beans-5.2.15.RELEASE.jar:5.2.15.RELEASE]
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:897) ~[spring-beans-5.2.15.RELEASE.jar:5.2.15.RELEASE]
        at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:879) ~[spring-context-5.2.15.RELEASE.jar:5.2.15.RELEASE]
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:551) ~[spring-context-5.2.15.RELEASE.jar:5.2.15.RELEASE]
        at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:143) ~[spring-boot-2.3.12.RELEASE.jar:2.3.12.RELEASE]
        at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:755) ~[spring-boot-2.3.12.RELEASE.jar:2.3.12.RELEASE]
        at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:747) ~[spring-boot-2.3.12.RELEASE.jar:2.3.12.RELEASE]
        at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:402) ~[spring-boot-2.3.12.RELEASE.jar:2.3.12.RELEASE]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:312) ~[spring-boot-2.3.12.RELEASE.jar:2.3.12.RELEASE]
        at org.springframework.boot.builder.SpringApplicationBuilder.run(SpringApplicationBuilder.java:140) ~[spring-boot-2.3.12.RELEASE.jar:2.3.12.RELEASE]
        at com.meread.selenium.GuideWebSocketApplication.main(GuideWebSocketApplication.java:20) ~[guide.jar:1.0]
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[na:na]
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[na:na]
        at java.base/java.lang.reflect.Method.invoke(Unknown Source) ~[na:na]
        at org.springframework.boot.devtools.restart.RestartLauncher.run(RestartLauncher.java:49) ~[spring-boot-devtools-2.3.12.RELEASE.jar:2.3.12.RELEASE]
Caused by: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'guideEventHandler': Unsatisfied dependency expressed through field 'wsProcessor'; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'guideWSProcessor': Unsatisfied dependency expressed through field 'nodeService'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'nodeService' defined in URL [jar:file:/jarlib/jd-qinglong-service-1.0.jar!/com/meread/selenium/service/NodeService.class]: Invocation of init method failed; nested exception is java.io.FileNotFoundException: class path resource [ql.db] cannot be opened because it does not exist
        at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.resolveFieldValue(AutowiredAnnotationBeanPostProcessor.java:660) ~[spring-beans-5.2.15.RELEASE.jar:5.2.15.RELEASE]
        at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:640) ~[spring-beans-5.2.15.RELEASE.jar:5.2.15.RELEASE]
        at org.springframework.beans.factory.annotation.InjectionMetadata.inject(InjectionMetadata.java:119) ~[spring-beans-5.2.15.RELEASE.jar:5.2.15.RELEASE]
        at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.postProcessProperties(AutowiredAnnotationBeanPostProcessor.java:399) ~[spring-beans-5.2.15.RELEASE.jar:5.2.15.RELEASE]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1425) ~[spring-beans-5.2.15.RELEASE.jar:5.2.15.RELEASE]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:593) ~[spring-beans-5.2.15.RELEASE.jar:5.2.15.RELEASE]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:516) ~[spring-beans-5.2.15.RELEASE.jar:5.2.15.RELEASE]
        at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:324) ~[spring-beans-5.2.15.RELEASE.jar:5.2.15.RELEASE]
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234) ~[spring-beans-5.2.15.RELEASE.jar:5.2.15.RELEASE]
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:322) ~[spring-beans-5.2.15.RELEASE.jar:5.2.15.RELEASE]
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:202) ~[spring-beans-5.2.15.RELEASE.jar:5.2.15.RELEASE]
        at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:276) ~[spring-beans-5.2.15.RELEASE.jar:5.2.15.RELEASE]
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1307) ~[spring-beans-5.2.15.RELEASE.jar:5.2.15.RELEASE]
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1227) ~[spring-beans-5.2.15.RELEASE.jar:5.2.15.RELEASE]
        at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.resolveFieldValue(AutowiredAnnotationBeanPostProcessor.java:657) ~[spring-beans-5.2.15.RELEASE.jar:5.2.15.RELEASE]
        ... 25 common frames omitted
Caused by: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'guideWSProcessor': Unsatisfied dependency expressed through field 'nodeService'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'nodeService' defined in URL [jar:file:/jarlib/jd-qinglong-service-1.0.jar!/com/meread/selenium/service/NodeService.class]: Invocation of init method failed; nested exception is java.io.FileNotFoundException: class path resource [ql.db] cannot be opened because it does not exist
        at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.resolveFieldValue(AutowiredAnnotationBeanPostProcessor.java:660) ~[spring-beans-5.2.15.RELEASE.jar:5.2.15.RELEASE]
        at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:640) ~[spring-beans-5.2.15.RELEASE.jar:5.2.15.RELEASE]
        at org.springframework.beans.factory.annotation.InjectionMetadata.inject(InjectionMetadata.java:119) ~[spring-beans-5.2.15.RELEASE.jar:5.2.15.RELEASE]
        at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.postProcessProperties(AutowiredAnnotationBeanPostProcessor.java:399) ~[spring-beans-5.2.15.RELEASE.jar:5.2.15.RELEASE]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1425) ~[spring-beans-5.2.15.RELEASE.jar:5.2.15.RELEASE]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:593) ~[spring-beans-5.2.15.RELEASE.jar:5.2.15.RELEASE]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:516) ~[spring-beans-5.2.15.RELEASE.jar:5.2.15.RELEASE]
        at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:324) ~[spring-beans-5.2.15.RELEASE.jar:5.2.15.RELEASE]
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234) ~[spring-beans-5.2.15.RELEASE.jar:5.2.15.RELEASE]
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:322) ~[spring-beans-5.2.15.RELEASE.jar:5.2.15.RELEASE]
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:202) ~[spring-beans-5.2.15.RELEASE.jar:5.2.15.RELEASE]
        at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:276) ~[spring-beans-5.2.15.RELEASE.jar:5.2.15.RELEASE]
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1307) ~[spring-beans-5.2.15.RELEASE.jar:5.2.15.RELEASE]
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1227) ~[spring-beans-5.2.15.RELEASE.jar:5.2.15.RELEASE]
        at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.resolveFieldValue(AutowiredAnnotationBeanPostProcessor.java:657) ~[spring-beans-5.2.15.RELEASE.jar:5.2.15.RELEASE]
        ... 39 common frames omitted
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'nodeService' defined in URL [jar:file:/jarlib/jd-qinglong-service-1.0.jar!/com/meread/selenium/service/NodeService.class]: Invocation of init method failed; nested exception is java.io.FileNotFoundException: class path resource [ql.db] cannot be opened because it does not exist
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1799) ~[spring-beans-5.2.15.RELEASE.jar:5.2.15.RELEASE]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:594) ~[spring-beans-5.2.15.RELEASE.jar:5.2.15.RELEASE]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:516) ~[spring-beans-5.2.15.RELEASE.jar:5.2.15.RELEASE]
        at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:324) ~[spring-beans-5.2.15.RELEASE.jar:5.2.15.RELEASE]
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234) ~[spring-beans-5.2.15.RELEASE.jar:5.2.15.RELEASE]
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:322) ~[spring-beans-5.2.15.RELEASE.jar:5.2.15.RELEASE]
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:202) ~[spring-beans-5.2.15.RELEASE.jar:5.2.15.RELEASE]
        at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:276) ~[spring-beans-5.2.15.RELEASE.jar:5.2.15.RELEASE]
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1307) ~[spring-beans-5.2.15.RELEASE.jar:5.2.15.RELEASE]
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1227) ~[spring-beans-5.2.15.RELEASE.jar:5.2.15.RELEASE]
        at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.resolveFieldValue(AutowiredAnnotationBeanPostProcessor.java:657) ~[spring-beans-5.2.15.RELEASE.jar:5.2.15.RELEASE]
        ... 53 common frames omitted
Caused by: java.io.FileNotFoundException: class path resource [ql.db] cannot be opened because it does not exist
        at org.springframework.core.io.ClassPathResource.getInputStream(ClassPathResource.java:187) ~[spring-core-5.2.15.RELEASE.jar:5.2.15.RELEASE]
        at com.meread.selenium.service.NodeService.afterPropertiesSet(NodeService.java:49) ~[jd-qinglong-service-1.0.jar:1.0]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1858) ~[spring-beans-5.2.15.RELEASE.jar:5.2.15.RELEASE]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1795) ~[spring-beans-5.2.15.RELEASE.jar:5.2.15.RELEASE]
        ... 63 common frames omitted

2021-10-30 12:03:31,890 INFO exited: guide (exit status 0; expected)
2021-10-30 20:03:33.171  INFO 10 --- [           main] o.s.s.concurrent.ThreadPoolTaskExecutor  : Initializing ExecutorService 'applicationTaskExecutor'
2021-10-30 20:03:33.202  INFO 10 --- [           main] c.meread.selenium.BaseWebDriverManager   : 最大资源数配置: maxSessionFromEnvFile = 2 maxSessionFromProps = 4
2021-10-30 20:03:33.204  INFO 10 --- [           main] c.meread.selenium.BaseWebDriverManager   : 最大资源数配置: CAPACITY = 2
2021-10-30 20:03:33.210  INFO 10 --- [           main] c.meread.selenium.BaseWebDriverManager   : 解析1套配置
2021-10-30 20:03:33.243  INFO 10 --- [           main] c.m.selenium.WebDriverManagerSelenoid    : 清理未关闭的session，获取最大容量
2021-10-30 20:03:33.243  INFO 10 --- [           main] c.m.selenium.WebDriverManagerSelenoid    : 清理未关闭的docker container
2021-10-30 20:03:33.589  INFO 10 --- [           main] c.m.selenium.WebDriverManagerSelenoid    : 初始化一半Chrome实例
2021/10/30 12:03:34 [-] [NEW_REQUEST] [unknown] [127.0.0.1]
2021/10/30 12:03:34 [-] [NEW_REQUEST_ACCEPTED] [unknown] [127.0.0.1]
2021/10/30 12:03:34 [0] [LOCATING_SERVICE] [chrome] []
2021/10/30 12:03:34 [-] [DEFAULT_VERSION] [Using default version: 89.0]
2021/10/30 12:03:34 [0] [USING_DOCKER] [chrome] [89.0]
2021/10/30 12:03:34 [0] [CREATING_CONTAINER] [selenoid/chrome:89.0]
2021/10/30 12:03:34 [0] [BAD_TIMEZONE] [Asia/Shanghai]
2021/10/30 12:03:34 [0] [STARTING_CONTAINER] [selenoid/chrome:89.0] [58b9395e1514bdc807a1547b77a0ba0da77b5e7c365d7719a4f042c226d1c5ac]
2021/10/30 12:03:34 [0] [CONTAINER_STARTED] [selenoid/chrome:89.0] [58b9395e1514bdc807a1547b77a0ba0da77b5e7c365d7719a4f042c226d1c5ac] [0.34s]
2021/10/30 12:04:04 [0] [REMOVING_CONTAINER] [58b9395e1514bdc807a1547b77a0ba0da77b5e7c365d7719a4f042c226d1c5ac]
2021/10/30 12:04:05 [0] [CONTAINER_REMOVED] [58b9395e1514bdc807a1547b77a0ba0da77b5e7c365d7719a4f042c226d1c5ac]
2021/10/30 12:04:05 [0] [SERVICE_STARTUP_FAILED] [wait: http://172.17.0.3:4444/ does not respond in 30s]
Exception in thread "pool-2-thread-1" org.openqa.selenium.SessionNotCreatedException: Could not start a new session. Response code 500. Message: wait: http://172.17.0.3:4444/ does not respond in 30s
Build info: version: '4.0.0-rc-2', revision: '8d1e4aa5ae'
System info: host: '5366c5154b76', ip: '172.19.0.2', os.name: 'Linux', os.arch: 'amd64', os.version: '4.18.0-240.el8.x86_64', java.version: '11.0.12'
Driver info: com.meread.selenium.util.CdpRemoteWebDriver
Command: [null, newSession {capabilities=[Capabilities {browserName: chrome, goog:chromeOptions: {args: [lang=zh-CN,zh,zh-TW,en-US,en, --disable-blink-features=Au..., --lang=zh-cn, --disable-gpu, --no-sandbox, --ignore-ssl-errors=yes, --ignore-certificate-errors, --allow-running-insecure-co..., start-maximized], excludeSwitches: [enable-automation], extensions: [], prefs: {credentials_enable_service: false, profile.password_manager_enabled: false}, useAutomationExtension: false}, selenoid:options: {enableLog: false, enableVNC: true, enableVideo: false, env: [LANG=zh_CN.UTF-8, LANGUAGE=zh:cn, LC_ALL=zh_CN.UTF-8], sessionTimeout: 3600s, timeZone: Asia/Shanghai}}], desiredCapabilities=Capabilities {browserName: chrome, enableVideo: false, goog:chromeOptions: {args: [lang=zh-CN,zh,zh-TW,en-US,en, --disable-blink-features=Au..., --lang=zh-cn, --disable-gpu, --no-sandbox, --ignore-ssl-errors=yes, --ignore-certificate-errors, --allow-running-insecure-co..., start-maximized], excludeSwitches: [enable-automation], extensions: [], prefs: {credentials_enable_service: false, profile.password_manager_enabled: false}, useAutomationExtension: false}, screenResolution: 512x650x24, selenoid:options: {enableLog: false, enableVNC: true, enableVideo: false, env: [LANG=zh_CN.UTF-8, LANGUAGE=zh:cn, LC_ALL=zh_CN.UTF-8], sessionTimeout: 3600s, timeZone: Asia/Shanghai}}}]
Capabilities {}
        at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:126)
        at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:84)
        at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:62)
        at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:156)
        at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:559)
        at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:246)
        at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:168)
        at com.meread.selenium.util.CdpRemoteWebDriver.<init>(CdpRemoteWebDriver.java:39)
        at com.meread.selenium.WebDriverManagerSelenoid.lambda$createChrome$0(WebDriverManagerSelenoid.java:285)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.base/java.lang.Thread.run(Unknown Source)
2021-10-30 20:04:06.269  INFO 10 --- [           main] c.m.selenium.WebDriverManagerSelenoid    : 请等待创建浏览器实例
2021-10-30 20:04:07.270  INFO 10 --- [           main] c.m.selenium.WebDriverManagerSelenoid    : 请等待创建浏览器实例
2021-10-30 20:04:08.270  INFO 10 --- [           main] c.m.selenium.WebDriverManagerSelenoid    : 请等待创建浏览器实例
2021-10-30 20:04:09.271  INFO 10 --- [           main] c.m.selenium.WebDriverManagerSelenoid    : 请等待创建浏览器实例

**Comment by mengniu8** [comment]
我的也是， 一直卡在：请等待创建浏览器实例

**Comment by hs20073** [comment]
补充一下，平台资源是2核4g，是在windows用vmware跑的
