### ISSUE TITLE
按教程安装镜像后，运行日志这样子，是什么情况

### ISSUE THREAD

**Issue by a727426900** [rubyangxg/jd-qinglong#63]
at org.springframework.boot.SpringApplication.refresh(SpringApplication.
java:747) ~[spring-boot-2.3.12.RELEASE.jar:2.3.12.RELEASE]                      
        at org.springframework.boot.SpringApplication.refreshContext(SpringAppli
cation.java:402) ~[spring-boot-2.3.12.RELEASE.jar:2.3.12.RELEASE]               
        at org.springframework.boot.SpringApplication.run(SpringApplication.java
:312) ~[spring-boot-2.3.12.RELEASE.jar:2.3.12.RELEASE]                          
        at org.springframework.boot.SpringApplication.run(SpringApplication.java
:1247) ~[spring-boot-2.3.12.RELEASE.jar:2.3.12.RELEASE]                         
        at org.springframework.boot.SpringApplication.run(SpringApplication.java
:1236) ~[spring-boot-2.3.12.RELEASE.jar:2.3.12.RELEASE]                         
        at com.meread.selenium.AiFlowApplication.main(AiFlowApplication.java:20)
 ~[classes!/:1.0]                                                               
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Nativ
e Method) ~[na:na]                                                              
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknow
n Source) ~[na:na]                                                              
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Un
known Source) ~[na:na]                                                          
        at java.base/java.lang.reflect.Method.invoke(Unknown Source) ~[na:na]   
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner
.java:49) ~[webapp.jar:1.0]                                                     
        at org.springframework.boot.loader.Launcher.launch(L2021-11-05 18:24:49,
414 INFO exited: webapp (exit status 1; not expected)

**Comment by sloganlau** [comment]
同样问题 怎么解决的呀
